🔀 :: (#12) company 엔티티 추가
GroupBy-Side-Project-GSP/bridge-server pull request #13
Opened 2022-02-22 19:47 UTC by lyutvs

close #12

2022-02-22 19:48 UTC, lyutvs commented
DB url 없다고 build failde 뜹니당 무시 해도 괜찮습니다

2022-02-23 09:09 UTC, 2kkeullim approved these changes

2022-02-23 09:19 UTC, skmn3 approved these changes

2022-02-23 09:28 UTC, skmn3 approved these changes

2022-02-23 09:28 UTC, skmn3 commented on src/main/java/com/gsp/bridge/domain/company/domain/Company.java
> +    private LocalDateTime sigUppDateTime;
아! 잘못본건가 했는데, signUpDateTime인것 같습니다! 확인 부탁드려요

2022-02-23 09:29 UTC, lyutvs commented on src/main/java/com/gsp/bridge/domain/company/domain/Company.java
> +    private LocalDateTime sigUppDateTime;
수정하겠습니다

2022-02-23 10:54 UTC, pllap requested changes

2022-02-23 10:54 UTC, pllap commented on src/main/java/com/gsp/bridge/infrastructure/s3/DefaultImage.java
> +	public static final String USER_PROFILE_IMAGE = "'a'";
들여쓰기가 탭 문자로 돼 있습니다!
'a'는 임시로 넣어두신 건가요?

2022-02-23 10:54 UTC, pllap commented on src/main/java/com/gsp/bridge/domain/company/domain/Company.java
> +    private LocalDateTime sigUpDateTime;
고치셨는데 아직 n이 빠져있는 것 같습니다!

2022-02-23 10:54 UTC, lyutvs commented on src/main/java/com/gsp/bridge/infrastructure/s3/DefaultImage.java
> +	public static final String USER_PROFILE_IMAGE = "'a'";
이거 깃허브에서만 이런 형식으로 보여요

2022-02-23 10:55 UTC, lyutvs commented on src/main/java/com/gsp/bridge/domain/company/domain/Company.java
> +    private LocalDateTime sigUpDateTime;
그러네요

2022-02-23 11:04 UTC, pllap approved these changes

2022-02-23 11:06 UTC, merged